#服务端口设置，默认是8080
server:
  port: 8080
#数据库设置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.198.129:3306/pmdemo?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: root
    platform: mysql
    #初始化数据（主要是超级管理用户角色及管理员账号,注：只有检测到spring.datasource.initialization-mode=ALWAYS配置后，再检测spring.datasource.schema之后，且配置的sql角本命令不为空，才会去执行schema和spring.datasource.data）
    schema: classpath:initialsql/schema.sql
    data: classpath:initialsql/data.sql
    sql-script-encoding: utf-8
    #initialization-mode: always
    #Druid数据源配置
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 3
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    suffix: .html
    prefix: classpath:/templates
  resources:
    static-locations: classpath:/static/,classpath:/templates/,classpath:/initialsql/
  mail:
    default-encoding: UTF-8
    host: smtp.sina.com
    password: 760628
    port: 25
    protocol: smtp
    username: chamulong@sina.com

#引入日志配置文件
logging:
  config: classpath:config/logback-spring.xml




